import type React from "react";

/** Shared inline style record for the docs-site shell and example sections. */
export const styles: Record<string, React.CSSProperties> = {
  page: {
    maxWidth: 1280,
    margin: "0 auto",
    padding: "28px 28px 48px",
  },
  pageCompact: {
    padding: "18px 14px 36px",
    overflowX: "hidden",
  },
  header: {
    marginBottom: 22,
    display: "flex",
    justifyContent: "space-between",
    gap: 24,
  },
  title: { fontSize: 30, fontWeight: 700, color: "#f5f7fb", marginBottom: 8 },
  lead: { fontSize: 15, color: "#a8adbd", lineHeight: 1.6, maxWidth: 820 },
  shell: {
    display: "grid",
    gridTemplateColumns: "260px minmax(0, 1fr)",
    gap: 22,
    alignItems: "start",
  },
  shellCompact: {
    gridTemplateColumns: "minmax(0, 1fr)",
    gap: 16,
  },
  nav: {
    position: "sticky",
    top: 18,
    display: "grid",
    gap: 6,
    borderRight: "1px solid #242938",
    paddingRight: 14,
  },
  navCompact: {
    position: "static",
    display: "flex",
    overflowX: "auto",
    borderRight: "none",
    borderBottom: "1px solid #242938",
    paddingRight: 0,
    paddingBottom: 10,
    gap: 8,
  },
  navTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#7dd3fc",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginBottom: 5,
  },
  navTitleCompact: { display: "none" },
  navButton: {
    border: "1px solid transparent",
    background: "transparent",
    color: "#c8d0e8",
    textAlign: "left",
    padding: "9px 10px",
    borderRadius: 8,
    cursor: "pointer",
    display: "grid",
    gap: 2,
  },
  navButtonCompact: {
    flex: "0 0 148px",
    padding: "8px 10px",
  },
  navButtonActive: {
    background: "#151a26",
    borderColor: "#2d3850",
    color: "#ffffff",
  },
  navButtonTitle: { fontSize: 13.5, fontWeight: 650 },
  navButtonMeta: { fontSize: 11.5, color: "#858da1" },
  architectureLink: {
    textDecoration: "none",
    marginTop: 8,
    borderTop: "1px solid #2d3850",
    borderRadius: 0,
    paddingTop: 12,
  },
  content: { minWidth: 0 },
  pageIntro: {
    paddingBottom: 18,
    marginBottom: 22,
    borderBottom: "1px solid #242938",
  },
  kicker: {
    fontSize: 12,
    color: "#7dd3fc",
    textTransform: "uppercase",
    letterSpacing: 0.7,
    marginBottom: 6,
  },
  pageTitle: {
    fontSize: 24,
    color: "#f5f7fb",
    marginBottom: 6,
  },
  pageSummary: {
    fontSize: 14,
    lineHeight: 1.6,
    color: "#a8adbd",
    maxWidth: 780,
  },
  narrative: {
    background: "#10141e",
    border: "1px solid #242938",
    borderRadius: 8,
    padding: "14px 16px",
    marginBottom: 18,
  },
  narrativeTitle: {
    color: "#dbeafe",
    fontSize: 15,
    marginBottom: 7,
  },
  referenceCard: {
    background: "#10141e",
    border: "1px solid #242938",
    borderRadius: 8,
    padding: "16px",
    marginBottom: 18,
  },
  referenceHeading: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    alignItems: "start",
  },
  referenceCode: { color: "#93c5fd", fontSize: 12 },
  referenceBadge: {
    maxWidth: 360,
    color: "#a7f3d0",
    background: "#10251f",
    border: "1px solid #245c4c",
    borderRadius: 999,
    padding: "5px 9px",
    fontSize: 11,
    lineHeight: 1.35,
  },
  referenceTable: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: 12,
    color: "#cbd5e1",
    fontSize: 12,
    textAlign: "left",
  },
  referenceKey: {
    width: 170,
    color: "#93c5fd",
    padding: "5px 10px 5px 0",
    textAlign: "left",
  },
  referenceLinks: { marginTop: 12, color: "#94a3b8", fontSize: 12 },
  referenceLink: { color: "#7dd3fc", marginLeft: 9 },
  example: {
    paddingBottom: 34,
    marginBottom: 36,
    borderBottom: "1px solid #202433",
  },
  exampleHeader: {
    display: "grid",
    gridTemplateColumns: "42px minmax(0, 1fr)",
    gap: 12,
    alignItems: "start",
    marginBottom: 14,
  },
  exampleIndex: {
    width: 34,
    height: 34,
    display: "grid",
    placeItems: "center",
    border: "1px solid #2d3850",
    borderRadius: 8,
    color: "#7dd3fc",
    fontSize: 12,
    fontWeight: 700,
  },
  exampleTitle: {
    fontSize: 18,
    fontWeight: 650,
    color: "#f5f7fb",
    marginBottom: 4,
  },
  exampleDescription: { fontSize: 13.5, color: "#a8adbd", lineHeight: 1.5 },
  datasetNote: {
    margin: "7px 0 0",
    color: "#8aa3c7",
    fontSize: 12,
    lineHeight: 1.45,
  },
  detailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 14,
    marginBottom: 14,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(320px, 0.92fr) minmax(360px, 1.08fr)",
    gap: 14,
    marginBottom: 14,
  },
  gridCompact: {
    gridTemplateColumns: "minmax(0, 1fr)",
  },
  panel: {
    background: "#121722",
    border: "1px solid #242938",
    borderRadius: 8,
    padding: 14,
    minWidth: 0,
  },
  panelTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#93c5fd",
    marginBottom: 9,
    textTransform: "uppercase",
    letterSpacing: 0.55,
  },
  bodyCopy: {
    fontSize: 13,
    color: "#d3d8e6",
    lineHeight: 1.55,
    marginBottom: 10,
  },
  metaCopy: { fontSize: 12.5, color: "#858da1", lineHeight: 1.5 },
  executionBadgeResident: {
    display: "inline-block",
    margin: "0 0 8px",
    padding: "5px 8px",
    border: "1px solid #245c4c",
    borderRadius: 999,
    background: "#10251f",
    color: "#a7f3d0",
    fontSize: 11.5,
    fontWeight: 700,
  },
  executionBadgePacked: {
    display: "inline-block",
    margin: "0 0 8px",
    padding: "5px 8px",
    border: "1px solid #33486a",
    borderRadius: 999,
    background: "#111d30",
    color: "#bfdbfe",
    fontSize: 11.5,
    fontWeight: 700,
  },
  actionLink: {
    display: "block",
    width: "fit-content",
    margin: "7px 0",
    color: "#7dd3fc",
    fontSize: 12.5,
    fontWeight: 650,
  },
  fileInput: {
    color: "#d3d8e6",
    fontSize: 12.5,
    margin: "8px 0 12px",
    maxWidth: "100%",
  },
  fileInputLabel: {
    margin: "14px 0 0",
    color: "#a8adbd",
    fontSize: 12.5,
  },
  modelFixtureLabel: {
    display: "grid",
    gap: 6,
    marginTop: 12,
    color: "#d3d8e6",
    fontSize: 12.5,
    fontWeight: 650,
  },
  modelFixtureSelect: {
    width: "min(100%, 420px)",
    padding: "7px 9px",
    border: "1px solid #3a465f",
    borderRadius: 5,
    color: "#e2e8f0",
    background: "#0f1725",
    font: "inherit",
  },
  errorCopy: { fontSize: 12.5, color: "#fca5a5", lineHeight: 1.5 },
  pre: {
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    fontSize: 12.5,
    color: "#d7def1",
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    overflowX: "auto",
  },
  note: { fontSize: 12, color: "#858da1", marginTop: 10, lineHeight: 1.5 },
  details: {
    background: "#10141e",
    border: "1px solid #242938",
    borderRadius: 8,
    padding: "12px 14px",
  },
  summary: {
    color: "#93c5fd",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 650,
    marginBottom: 10,
  },
  tableWrap: { overflowX: "auto" },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 12.5,
  },
  th: {
    color: "#93c5fd",
    textAlign: "left",
    padding: "0 10px 7px 0",
    borderBottom: "1px solid #2d3850",
    fontWeight: 700,
  },
  td: {
    color: "#d3d8e6",
    padding: "7px 10px 0 0",
    whiteSpace: "nowrap",
  },
  tableNote: {
    fontSize: 11.5,
    color: "#858da1",
    marginTop: 8,
  },
};
