// 3D emission parity with the 2D emit/mod.ts contract: a standalone,
// statically-importable module of use.gpu Plot components. Positions are
// serialized DATA-space vec4; the Cartesian range + camera matrix project on
// the GPU, so the emitted source carries no per-point projection either.
import type { Render3DNode } from "./types.ts";

const identifier = (name: string): string => {
  const safe = name.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(safe) ? safe : `_${safe}`;
};

export function emitPoint3dSource(
  node: Render3DNode,
  name = "PointCloud3D",
): string {
  const positions = Array.from(node.positions.array);
  const colors = node.colors ? Array.from(node.colors.array) : undefined;
  const sizes = node.sizes ? Array.from(node.sizes.array) : undefined;
  // use.gpu Cartesian ranges are 4-component; append the homogeneous w axis.
  const range = [...node.range, [0, 1]];
  const pointProps = [
    `positions={${JSON.stringify(positions)}}`,
    colors
      ? `colors={${JSON.stringify(colors)}}`
      : `color=${JSON.stringify(node.color)}`,
    sizes ? `sizes={${JSON.stringify(sizes)}}` : `size={${node.size}}`,
    `opacity={${node.opacity}}`,
    `depthTest={${node.depthTest}}`,
    `formats={{ positions: "vec4<f32>" }}`,
  ].join("\n      ");
  return `/** @jsxRuntime classic */
/** @jsx createElement */
import { createElement } from "@use-gpu/live";
import { Cartesian, Point } from "@use-gpu/plot";

// Generated by @gggplot/core geom_3d. Positions are DATA-space vec4; the
// Cartesian range and camera matrix project them on the GPU.
export const ${identifier(name)} = () => (
  <Cartesian
    range={${JSON.stringify(range)}}
    matrix={${JSON.stringify(node.cameraMatrix)}}
  >
    <Point
      ${pointProps}
    />
  </Cartesian>
);
`;
}
