export interface GeomExampleCoverage {
  exampleIds: readonly string[];
  mode: "dedicated" | "comparison";
}

/** Public constructor aliases resolved to the core geom definition they lower through. */
export const geomConstructorKinds = {
  geomPoint: "point",
  geomLine: "line",
  geomPath: "path",
  geomBar: "bar",
  geomHistogram: "bar",
  geomCol: "col",
  geomArea: "area",
  geomRibbon: "ribbon",
  geomPolygon: "polygon",
  geomTile: "tile",
  geomRaster: "tile",
  geomText: "text",
  geomLabel: "label",
  geomBoxplot: "boxplot",
  geomErrorbar: "errorbar",
  geomErrorbarh: "errorbar",
  geomLinerange: "linerange",
  geomPointrange: "pointrange",
  geomCrossbar: "crossbar",
  geomSmooth: "smooth",
  geomDensity: "line",
  geomDensity2d: "segment",
  geomDensity2dFilled: "tile",
  geomEcdf: "step",
  geomViolin: "violin",
  geomDotplot: "dotplot",
  geomBin2d: "tile",
  geomHex: "hex",
  geomWaffle: "tile",
  geomQq: "point",
  geomQqLine: "line",
  geomQuantile: "line",
  geomContour: "segment",
  geomContourFilled: "tile",
  geomCount: "point",
  geomFreqpoly: "line",
  geomBlank: "blank",
  geomStep: "step",
  geomCurve: "curve",
  geomSpoke: "spoke",
  geomRug: "rug",
  geomFunction: "line",
  geomJitter: "point",
  geomHline: "hline",
  geomVline: "vline",
  geomAbline: "abline",
} as const;

export const geomConstructorDefaults: Readonly<
  Record<string, { stat?: string; position?: string }>
> = {
  geomHistogram: { stat: "bin" },
  geomDensity: { stat: "density" },
  geomDensity2d: { stat: "density2d" },
  geomDensity2dFilled: { stat: "density2dfilled" },
  geomEcdf: { stat: "ecdf" },
  geomBin2d: { stat: "bin2d" },
  geomWaffle: { stat: "waffle" },
  geomQq: { stat: "qq" },
  geomQqLine: { stat: "qqline" },
  geomQuantile: { stat: "quantile" },
  geomContour: { stat: "contour" },
  geomContourFilled: { stat: "contourfilled" },
  geomCount: { stat: "sum" },
  geomFreqpoly: { stat: "bin" },
  geomFunction: { stat: "function" },
  geomJitter: { position: "jitter" },
};

/** Public geom constructor -> docs examples where it is a primary subject. */
export const geomExampleCoverage: Readonly<
  Record<string, GeomExampleCoverage>
> = {
  geomPoint: { exampleIds: ["ScatterLine"], mode: "comparison" },
  geomLine: { exampleIds: ["ScatterLine"], mode: "comparison" },
  geomPath: { exampleIds: ["PathOrder"], mode: "dedicated" },
  geomBar: { exampleIds: ["CountStackedBar"], mode: "dedicated" },
  geomHistogram: { exampleIds: ["HistogramStatBin"], mode: "dedicated" },
  geomCol: { exampleIds: ["FlippedBars"], mode: "dedicated" },
  geomArea: { exampleIds: ["AreaAndRibbon"], mode: "comparison" },
  geomRibbon: { exampleIds: ["AreaAndRibbon"], mode: "comparison" },
  geomPolygon: { exampleIds: ["PolygonShapes"], mode: "dedicated" },
  geomTile: { exampleIds: ["TileHeatmap"], mode: "dedicated" },
  geomRaster: { exampleIds: ["RasterGrid"], mode: "dedicated" },
  geomText: { exampleIds: ["ThemedChart"], mode: "comparison" },
  geomLabel: {
    exampleIds: ["LabelsAndIntervals", "LabelBackgrounds"],
    mode: "comparison",
  },
  geomBoxplot: { exampleIds: ["BoxplotReference"], mode: "dedicated" },
  geomErrorbar: { exampleIds: ["LabelsAndIntervals"], mode: "comparison" },
  geomErrorbarh: { exampleIds: ["IntervalFamily"], mode: "comparison" },
  geomLinerange: { exampleIds: ["IntervalFamily"], mode: "comparison" },
  geomPointrange: { exampleIds: ["IntervalFamily"], mode: "comparison" },
  geomCrossbar: { exampleIds: ["IntervalFamily"], mode: "comparison" },
  geomSmooth: { exampleIds: ["SmoothLm"], mode: "dedicated" },
  geomDensity: { exampleIds: ["DensityCurve"], mode: "dedicated" },
  geomDensity2d: { exampleIds: ["Density2dContours"], mode: "comparison" },
  geomDensity2dFilled: {
    exampleIds: ["Density2dContours"],
    mode: "comparison",
  },
  geomEcdf: { exampleIds: ["EmpiricalCdf"], mode: "dedicated" },
  geomViolin: { exampleIds: ["ViolinReference"], mode: "dedicated" },
  geomDotplot: { exampleIds: ["ViolinAndDots"], mode: "comparison" },
  geomBin2d: { exampleIds: ["RectangularAndHexBins"], mode: "comparison" },
  geomHex: { exampleIds: ["RectangularAndHexBins"], mode: "comparison" },
  geomWaffle: { exampleIds: ["WaffleChart"], mode: "dedicated" },
  geomQq: { exampleIds: ["QqDiagnostics"], mode: "comparison" },
  geomQqLine: { exampleIds: ["QqDiagnostics"], mode: "comparison" },
  geomQuantile: { exampleIds: ["QuantileRegression"], mode: "dedicated" },
  geomContour: { exampleIds: ["ContourBands"], mode: "comparison" },
  geomContourFilled: { exampleIds: ["ContourBands"], mode: "comparison" },
  geomCount: { exampleIds: ["CountedPoints"], mode: "dedicated" },
  geomFreqpoly: { exampleIds: ["FreqpolyAndJitter"], mode: "comparison" },
  geomBlank: { exampleIds: ["FunctionAndBlank"], mode: "comparison" },
  geomStep: { exampleIds: ["ConnectedGeomVariants"], mode: "comparison" },
  geomCurve: { exampleIds: ["ConnectedGeomVariants"], mode: "comparison" },
  geomSpoke: { exampleIds: ["ConnectedGeomVariants"], mode: "comparison" },
  geomRug: { exampleIds: ["ConnectedGeomVariants"], mode: "comparison" },
  geomFunction: { exampleIds: ["FunctionAndBlank"], mode: "comparison" },
  geomJitter: { exampleIds: ["FreqpolyAndJitter"], mode: "comparison" },
  geomHline: { exampleIds: ["AnnotationComposite"], mode: "comparison" },
  geomVline: { exampleIds: ["AnnotationComposite"], mode: "comparison" },
  geomAbline: { exampleIds: ["AnnotationComposite"], mode: "comparison" },
};
