import type { ModelInspectionExample } from "./types.ts";

/** A small, deterministic graph used by the docs and page-level validation. */
export const tinyMlpInspection: ModelInspectionExample = {
  id: "TinyMlpInspection",
  title: "Model structure and GPU residency",
  description:
    "A tiny ONNX-shaped MLP document shows how graph structure, tensor metadata, and post-loading storage stay separate.",
  ownership: "visualizer-owned",
  ownershipReason:
    "The first docs slice keeps visualization storage in useGPU-owned buffers. A runtime-shared buffer is an optional optimization that requires same-device and layout validation.",
  document: {
    schema: "gggplot.model@1",
    id: "tiny-mlp",
    name: "Tiny MLP fixture",
    framework: { name: "ONNX", dialect: "fixture" },
    source: {
      id: "tiny-mlp.onnx",
      kind: "memory",
      format: "onnx",
      version: "fixture-v1",
    },
    graphs: [{
      id: "main",
      name: "main graph",
      inputs: [{ id: "input", dtype: "f32", shape: [1, 4] }],
      outputs: [{
        id: "output",
        tensorId: "output",
        dtype: "f32",
        shape: [1, 2],
      }],
      nodes: [
        {
          id: "linear-1",
          kind: "operator",
          op: "Gemm",
          name: "projection",
          inputs: [{ id: "input", dtype: "f32", shape: [1, 4] }],
          outputs: [{
            id: "hidden",
            tensorId: "hidden",
            dtype: "f32",
            shape: [1, 4],
          }],
          parameters: ["weights-1", "bias-1"],
        },
        {
          id: "relu",
          kind: "operator",
          op: "Relu",
          inputs: [{
            id: "hidden",
            tensorId: "hidden",
            dtype: "f32",
            shape: [1, 4],
          }],
          outputs: [{
            id: "activated",
            tensorId: "activated",
            dtype: "f32",
            shape: [1, 4],
          }],
        },
        {
          id: "linear-2",
          kind: "operator",
          op: "Gemm",
          name: "classifier",
          inputs: [{
            id: "activated",
            tensorId: "activated",
            dtype: "f32",
            shape: [1, 4],
          }],
          outputs: [{
            id: "output",
            tensorId: "output",
            dtype: "f32",
            shape: [1, 2],
          }],
          parameters: ["weights-2", "bias-2"],
        },
      ],
      edges: [
        { id: "input-hidden", from: "linear-1", to: "relu", valueId: "hidden" },
        {
          id: "hidden-activated",
          from: "relu",
          to: "linear-2",
          valueId: "activated",
        },
      ],
    }],
    tensors: {
      "weights-1": {
        id: "weights-1",
        name: "projection.weight",
        dtype: "f32",
        shape: [4, 4],
        role: "parameter",
        byteLength: 64,
        residency: {
          policy: "range",
          cacheKey: "tiny-mlp:weights-1",
          upload: "on-demand",
          maxBytes: 4096,
          readback: "explicit",
        },
        summary: { count: 16, finiteCount: 16, min: -0.5, max: 0.5, mean: 0 },
      },
      "bias-1": {
        id: "bias-1",
        name: "projection.bias",
        dtype: "f32",
        shape: [4],
        role: "parameter",
        byteLength: 16,
        residency: {
          policy: "metadata",
          cacheKey: "tiny-mlp:bias-1",
          upload: "never",
          readback: "summary-only",
        },
      },
      "weights-2": {
        id: "weights-2",
        name: "classifier.weight",
        dtype: "f32",
        shape: [2, 4],
        role: "parameter",
        byteLength: 32,
        residency: {
          policy: "range",
          cacheKey: "tiny-mlp:weights-2",
          upload: "on-demand",
          maxBytes: 4096,
          readback: "explicit",
        },
        summary: { count: 8, finiteCount: 8, min: -0.5, max: 0.5, mean: 0 },
      },
      "bias-2": {
        id: "bias-2",
        name: "classifier.bias",
        dtype: "f32",
        shape: [2],
        role: "parameter",
        byteLength: 8,
        residency: {
          policy: "metadata",
          cacheKey: "tiny-mlp:bias-2",
          upload: "never",
          readback: "summary-only",
        },
      },
      hidden: {
        id: "hidden",
        dtype: "f32",
        shape: [1, 4],
        role: "intermediate",
        residency: {
          policy: "range",
          cacheKey: "tiny-mlp:hidden",
          upload: "on-demand",
          maxBytes: 1024,
          readback: "summary-only",
        },
      },
      activated: {
        id: "activated",
        dtype: "f32",
        shape: [1, 4],
        role: "activation",
        residency: {
          policy: "range",
          cacheKey: "tiny-mlp:activated",
          upload: "on-demand",
          maxBytes: 1024,
          readback: "summary-only",
        },
      },
      output: {
        id: "output",
        dtype: "f32",
        shape: [1, 2],
        role: "output",
        residency: {
          policy: "metadata",
          cacheKey: "tiny-mlp:output",
          upload: "never",
          readback: "summary-only",
        },
      },
    },
  },
};
