// Source-emit backend — turns a RenderTree into standalone UseGPU Live .tsx
// source. This is the literal "transpiler": ggplot spec in, UseGPU JSX out.

import type { ComponentName, RenderNode } from "../compile/rendertree.ts";

const PLOT_IMPORTS: ComponentName[] = [
  "Plot",
  "Embedded",
  "Cartesian",
  "Polar",
  "Axis",
  "Grid",
  "Point",
  "Line",
  "Face",
  "Polygon",
  "Label",
];

// "FacetGrid" isn't a real @use-gpu/plot export (see rendertree.ts and
// render/GGPlot.tsx's Live implementation, which this mirrors) — when a
// faceted spec uses it, emitSource inlines this plain-JS definition plus its
// extra imports so the generated module is still standalone.
const FACET_GRID_SOURCE = `
// Not a real @use-gpu/plot export -- divides the ambient LayoutContext pixel
// rect into an nrow x ncol grid and provides each cell as the LayoutContext
// for one child <Embedded>, giving facet_wrap/facet_grid their panel layout.
const FacetGrid = ({ nrow, ncol, gap = 0, children }) => {
  const kids = Array.isArray(children) ? children : children != null ? [children] : [];
  const [left, top, right, bottom] = useContext(LayoutContext);
  const cellW = (right - left) / ncol;
  const cellH = (bottom - top) / nrow;
  return createElement(
    Fragment,
    {},
    ...kids.map((child, i) => {
      const row = Math.floor(i / ncol);
      const col = i % ncol;
      const cell = [
        left + col * cellW + gap / 2,
        top + row * cellH + gap / 2,
        left + (col + 1) * cellW - gap / 2,
        top + (row + 1) * cellH - gap / 2,
      ];
      return provide(LayoutContext, cell, child);
    }),
  );
};
`;

function formatProp(key: string, value: unknown): string {
  if (typeof value === "string") return `${key}=${JSON.stringify(value)}`;
  return `${key}={${JSON.stringify(value)}}`;
}

function emitNode(n: RenderNode, indent: string): string {
  const props = Object.entries(n.props)
    .map(([k, v]) => formatProp(k, v))
    .join(" ");
  const open = props ? `${n.component} ${props}` : n.component;

  if (n.children.length === 0) return `${indent}<${open} />`;

  const children = n.children.map((c) => emitNode(c, indent + "  ")).join("\n");
  return `${indent}<${open}>\n${children}\n${indent}</${n.component}>`;
}

/** Collect the plot component names actually used, for a tidy import line. */
function usedComponents(root: RenderNode, seen = new Set<ComponentName>()): Set<ComponentName> {
  seen.add(root.component);
  for (const c of root.children) usedComponents(c, seen);
  return seen;
}

/** Emit a complete, self-contained UseGPU Live component module. */
export function emitSource(root: RenderNode, name = "GGChart"): string {
  const all = usedComponents(root);
  const used = PLOT_IMPORTS.filter((c) => all.has(c));
  const faceted = all.has("FacetGrid");

  const liveImports = faceted ? "createElement, Fragment, provide, useContext" : "createElement, Fragment";
  const workbenchImport = faceted ? `\nimport { LayoutContext } from "@use-gpu/workbench";` : "";
  const facetGridDef = faceted ? `\n${FACET_GRID_SOURCE}` : "";

  return `/** @jsxRuntime classic */
/** @jsx createElement */
/** @jsxFrag Fragment */
import { ${liveImports} } from "@use-gpu/live";
import { ${used.join(", ")} } from "@use-gpu/plot";${workbenchImport}
${facetGridDef}
// Generated by @gggplot/core. Do not edit by hand.
export const ${name} = () => (
${emitNode(root, "  ")}
);
`;
}
