// Source-emit backend — turns a RenderTree into standalone UseGPU Live .tsx
// source. This is the literal "transpiler": ggplot spec in, UseGPU JSX out.

import type { ComponentName, RenderNode } from "../compile/rendertree.ts";

const PLOT_IMPORTS: ComponentName[] = [
  "Plot",
  "Cartesian",
  "Polar",
  "Axis",
  "Grid",
  "Point",
  "Line",
  "Face",
  "Polygon",
  "Label",
];

function formatProp(key: string, value: unknown): string {
  if (typeof value === "string") return `${key}=${JSON.stringify(value)}`;
  return `${key}={${JSON.stringify(value)}}`;
}

function emitNode(n: RenderNode, indent: string): string {
  const props = Object.entries(n.props)
    .map(([k, v]) => formatProp(k, v))
    .join(" ");
  const open = props ? `${n.component} ${props}` : n.component;

  if (n.children.length === 0) return `${indent}<${open} />`;

  const children = n.children.map((c) => emitNode(c, indent + "  ")).join("\n");
  return `${indent}<${open}>\n${children}\n${indent}</${n.component}>`;
}

/** Collect the plot component names actually used, for a tidy import line. */
function usedComponents(root: RenderNode, seen = new Set<ComponentName>()): Set<ComponentName> {
  seen.add(root.component);
  for (const c of root.children) usedComponents(c, seen);
  return seen;
}

/** Emit a complete, self-contained UseGPU Live component module. */
export function emitSource(root: RenderNode, name = "GGChart"): string {
  const used = PLOT_IMPORTS.filter((c) => usedComponents(root).has(c));
  return `/** @jsxRuntime classic */
/** @jsx createElement */
/** @jsxFrag Fragment */
import { createElement, Fragment } from "@use-gpu/live";
import { ${used.join(", ")} } from "@use-gpu/plot";

// Generated by @gggplot/core. Do not edit by hand.
export const ${name} = () => (
${emitNode(root, "  ")}
);
`;
}
