import type { ExtensionRegistry } from "@gggplot/core/plan";
import type { PointCloudRenderNode } from "./types.ts";

const identifier = (name: string): string => {
  const safe = name.replace(/[^A-Za-z0-9_$]/g, "_");
  return /^[A-Za-z_$]/.test(safe) ? safe : `_${safe}`;
};

/** Emit a standalone static import; neither closures nor registry values serialize. */
export function emitPointCloudSource(
  node: PointCloudRenderNode,
  registry: ExtensionRegistry,
  name = "PointCloudChart",
): string {
  const adapter = registry.resolveEmit(node.component).adapters.emit;
  const props = {
    ...node.props,
    positions: Array.from(node.props.positions),
    ...(node.props.colors ? { colors: Array.from(node.props.colors) } : {}),
    ...(node.props.sizes ? { sizes: Array.from(node.props.sizes) } : {}),
  };
  return `/** @jsxRuntime classic */
/** @jsx createElement */
import { createElement } from "@use-gpu/live";
import { ${adapter.exportName} } from ${JSON.stringify(adapter.importFrom)};

// Generated by @gggplot/3d. The spec contains only data and a versioned id.
export const ${identifier(name)} = () => (
  <${adapter.exportName} {...${JSON.stringify(props)}} />
);
`;
}
